[package]
name = "zKitap2Pdf"
version = "0.1.4"
edition = "2024"
description = "zKitap2pdf is a tool for converting Fernus Z-kitap e-books from exe to pdf format using ruffle"
authors = ["Vrdons <vrdons@proton.me>", "ErenayDev <erenaydev@proton.me>"]
license = "MIT"
repository = "https://github.com/vrdons/zKitap2Pdf"
homepage = "https://github.com/vrdons/zKitap2Pdf"
readme = "README.md"
keywords = ["zKitap", "pdf", "ruffle", "zKitap2Pdf"]
rust-version = "1.88"
exclude = [
    "target/",
    ".git/",
    ".github/",
    "tools/",
    "*.pdf",
    "in/"
]

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive"] }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
notify = "8.2.0"
walkdir = "2.5.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
swf = { git = "https://github.com/ruffle-rs/ruffle.git", package = "swf", rev = "a1ac4ce8647352ad03044031cad0454a636427b8" }
ruffle_core = { git = "https://github.com/ruffle-rs/ruffle.git", package = "ruffle_core", features = ["deterministic", "default_font"], rev = "a1ac4ce8647352ad03044031cad0454a636427b8" }
ruffle_render_wgpu = { git = "https://github.com/ruffle-rs/ruffle.git", package = "ruffle_render_wgpu", features = ["clap"], rev = "a1ac4ce8647352ad03044031cad0454a636427b8" }
futures = "0.3.32"
oxidize-pdf = "2.12.0"
tempfile = "3.25.0"
base64 = "0.23.0"
hex = "0.4.3"
blowfish = "0.10.0"
cipher = "0.5.2"
flate2 = "1.0.35"
lzma-rs = { version = "0.3.0", features = ["raw_decoder"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-{ version }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"

[package.metadata.generate-rpm]
assets = [
  { source = "target/release/zKitap2Pdf", dest = "/usr/bin/zKitap2Pdf", mode = "755" },
]
summary = "Convert Fernus Z-kitap e-books EXE's to PDF"
description = """
zKitap2Pdf is a tool for converting Fernus Z-kitap e-books from exe to pdf format. Using ruffle
"""
license = "MIT"

[package.metadata.deb]
maintainer = "Vrdons <vrodns@proton.me>"
copyright = "2026, Vrdons <vrdons@proton.me>"
extended-description = """
zKitap2Pdf is a tool for converting Fernus Z-kitap e-books from exe to pdf format using ruffle
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/zKitap2Pdf", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/zKitap2Pdf/", "644"],
]
